# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Evan Ma
description:      '<a href="https://www.yale-nus.edu.sg/">Yale-NUS College</a> student'
baseurl:          /
gems:			  
- jekyll-paginate
- redcarpet
- jekyll-gist

author:
  name:           'Evan Ma'
  url:            https://twitter.com/evanma2014

paginate:         5

github:
  repo:           https://github.com/evanma92
